name: Android Cloud Compiler Engine

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to manually click a "Build" button on GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Source
      uses: actions/checkout@v4

    - name: Set up Java JDK Environment
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant Execute Permission for Gradle
      run: chmod +x gradlew

    - name: Compile Production APK & AAB Bundle
      run: ./gradlew assembleRelease bundleRelease

    - name: Upload Finished APK (For Testing)
      uses: actions/upload-artifact@v4
      with:
        name: Production-Testing-APK
        path: app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Upload Finished AAB (For Google Play Store)
      uses: actions/upload-artifact@v4
      with:
        name: Play-Store-Bundle-AAB
        path: app/build/outputs/bundle/release/app-release.aab
